Updated Readme.md
iv22/dailytracker pull request #3
Opened 2021-02-07 20:36 UTC by Nadzechka

2021-02-09 19:45 UTC, Nadzechka commented
Requirements and Install sections completed

2021-02-13 10:42 UTC, anatoliliotych requested changes

2021-02-13 10:42 UTC, anatoliliotych commented on README.md
> +- RoR version 6.0.3.4
ror is old name for rails, so stop using it :)

2021-02-15 16:57 UTC, anatoliliotych commented
Please, fix git history this PR looks dirty from git point of view. We don't merge master to feature branch, we amend commits, we respect git history. @Nadzechka

2021-02-20 18:24 UTC, closed without merging